#!python
#!/usr/bin/env python3

rule targets:
    input:
       "output/cluster_summary.txt"

rule download_data:
    input: 
        input_file = "code/s01_download_data.sh"
        
    output: 
        output_file = directory("./data/raw")

    shell:"""
        sh code/s01_download_data.sh
    """

rule pca:
    input: 
        input_file = "data/raw"
        
    output: 
        output_file = "output/cluster_summary.txt"

    shell:"""
        Rscript code/s02_PCA.R
    """

rule clustering:
    input: 
        input_file = "data/raw"
        
    output: 
        output_file = "output/cluster_summary.txt"

    shell:"""
        Rscript code/s03_data_analysis.R
    """

